## Studi Kasus

ada sebuah rumah yang berada tepat di tengah perbatasan antara Kota Bandung dan Kabupaten Bandung, sehingga pemerintah kesulitan untuk menentukan apakah rumah tersebut termasuk kedalam wilayah Kota Bandung atau Kabupaten Bandung.

Kita bisa menentukannya dengan menggunakan Algoritma k-NN, yaitu dengan melibatkan jarak antara rumah tersebut dengan rumah-rumah yang ada disekitarnya (tetangganya).

- Pertama, kita harus menentukan jumlah tetangga yg akan kita perhitungkan (k), misalnya kita tentukan 3 tetangga terdekat (k = 3).

- Kedua, hitung jarak setiap tetangga terhadap rumah tersebut, lalu urutkan hasilnya berdasarkan jarak, mulai dari yang terkecil ke yang terbesar.

- Ketiga, ambil 3 (k) tetangga yg paling dekat, lalu kita lihat masing-masing dari tetangga tersebut apakah termasuk kedalam wilayah Kota atau Kabupaten. Ada 2 kemungkinan:

    - Bila dari 3 tetangga tersebut terdapat ada 2 rumah yg termasuk kedalam wilayah Kota Bandung, maka rumah tersebut termasuk kedalam wilayah Kota Bandung.
    
    - Sebaliknya, bila dari 3 tetangga tersebut terdapat 2 rumah yg termasuk kedalam wilayah Kabupaten Bandung, maka rumah tersebut termasuk kedalam wilayah Kabupaten Bandung.

## Sample Dataset

In [44]:
import pandas as pd

rumah_df = pd.read_csv('../dataset/rumah.csv')
rumah_df

rumah  lat  long     lokasi
0      A   11    26       Kota
1      B   15    29       Kota
2      C   19    28       Kota
3      D   18    30       Kota
4      E   16    26       Kota
5      F   23    25  Kabupaten
6      G   25    22  Kabupaten
7      H   21    24  Kabupaten
8      I   23    25  Kabupaten
9      J   29    24  Kabupaten
10     X   19    25          ?

## Euclidience distance

In [45]:
import numpy as np

rumah_df = rumah_df.drop([0,10])
X_train = np.array(rumah_df[['lat','long']])
X_train

array([[15, 29],
       [19, 28],
       [18, 30],
       [16, 26],
       [23, 25],
       [25, 22],
       [21, 24],
       [23, 25],
       [29, 24]])

In [46]:
from scipy.spatial.distance import euclidean

misterius = np.array([19,25])

data_jarak = [euclidean(misterius,i) for i in X_train]

In [47]:
rumah_df['jarak'] = data_jarak
rumah_df.sort_values(['jarak'])


rumah  lat  long     lokasi      jarak
7     H   21    24  Kabupaten   2.236068
2     C   19    28       Kota   3.000000
4     E   16    26       Kota   3.162278
5     F   23    25  Kabupaten   4.000000
8     I   23    25  Kabupaten   4.000000
3     D   18    30       Kota   5.099020
1     B   15    29       Kota   5.656854
6     G   25    22  Kabupaten   6.708204
9     J   29    24  Kabupaten  10.049876

## with sklearn

In [48]:
rumah_df2 = pd.read_csv('../dataset/rumah.csv')
rumah_df2 = rumah_df2.drop([0,10])
y = np.array(rumah_df2[['lokasi']])



In [49]:
from sklearn.preprocessing import LabelBinarizer

lb = LabelBinarizer()

y_train = lb.fit_transform(y)
y_train.flatten()

array([1, 1, 1, 1, 0, 0, 0, 0, 0])

## train KNN Classification Model

In [50]:
from sklearn.neighbors import KNeighborsClassifier

K = 3
model = KNeighborsClassifier(n_neighbors=K)
model.fit(X=X_train,y=y_train)


/home/rizkyd/course/python/machine_learning/linear-regresion/env/lib/python3.8/site-packages/sklearn/neighbors/_classification.py:200: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=3)

In [51]:
X_new = np.array([19,25]).reshape(1,-1)
X_new

array([[19, 25]])

## predict

In [53]:
y_new = model.predict(X_new)
lb.inverse_transform(y_new)

array(['Kota'], dtype='<U9')